language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - development
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
env:
  global:
  - secure: Y0KXTULlC3K5z7D9bmGux5m1GuCxcnNd2nB6D5mcq2mtpHS17qjkfnvWuBa8BgbgatrK5yu0WFSjH0TXHnjPlMCXw6gDmFJ7HjbIjCKtYC36cbNnGzIpgyG80SARqLA90XvPrN+XPptv71kqEbP9zjSMYWQPM6fU94+/oUafI90=
  - secure: BEBHrFq7leUfbdL0ayFkfhdNwR/mtYXxSD8q2j3184fa9O6M7ombzUXN+4uLeXIrak5RA16EsrZRkI0pqhz9QJXA3kF/nWSrbO0sAEWFC8b6pKFq1huB8fsvcFnVqy5561GETzApOQPlOkH5Pv1qgRhssqTWa/6vbOgzemaaVcE=
