language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - martin.oconnor@stanford.edu
    on_success: never
    on_failure: always
env:
  global:
  - secure: YPYHq9zCeSDs62FG/dMRhBVThP7UW/4AYx06h0MId5u7MIbBnBIn+xdYTYHXaJpLu5TdkoA0lMyMRbf3eXtCavQ78vZhvsnc/aVgjGzE1Oqr4AwdyP68QhvK79TpfOXe8pMR4usGfHfhByLkzXmZKf1GxpMH5zRbGzruWI/p+rc=
  - secure: T4FrWYgn5TrTA5t3nk3bEbox+RKGBbPekd87PnRLUjDhy73yTEyNOS7+XtwYBc70gl5OjJM9Ys85M1Vd7FP2EH0p0ErKd/jsJjtBkkN36eaFSAvtDJxt2W5iUUonulTQvCaQ39eoQNndZW3tjWA8VniWE/25By8jeskEXH+XXek=
